modLoader="javafml"
loaderVersion="[28,)"
license="MIT"

logoFile=""
[[mods]]
modId="compmod"
version="1.1.2"
displayName="Yoshio'compMod"
displayURL=""
updateJSONURL=""
credits=""
authors=""
description=""
