modLoader="javafml"
loaderVersion="[28,)"
license="MIT"

logoFile="fenceslogo.png"
[[mods]]
modId="compmod"
version="1.1.2"
displayName="Yoshio'compMod"
displayURL=""
updateJSONURL=""
credits=""
authors=""
description=""
